# Generated by Django 4.1 on 2022-08-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rword", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="wordlist", table="random_word",),
    ]
