# Generated by Django 4.1 on 2022-08-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rword", "0002_alter_wordlist_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="wordlist", table="randomword",),
    ]
